CREATE dbo.SKU(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Code AS 's' + CAST(ID AS NVARCHAR(10)),
	Name NVARCHAR(100),
	CONSTRAINT UQ_SKU_Code UNIQUE (Code)
);

CREATE dbo.Family(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	SurName NVARCHAR(100),
	BudgetValue MONEY
);

CREATE dbo.Basket(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	ID_SKU INT,
	ID_Family INT,
	Quantity INT CHECK(Quantity >= 0),
	Value INT CHECK(Value >= 0),
	PurchaseDate DATETIME DEFAULT GETDATE(),
	DiscountValue INT,
	FOREIGN KEY (ID_SKU) REFERENCES dbo.SKU(ID),
	FOREIGN KEY (ID_Family) REFERENCES dbo.Family(ID)
);